---
nmcli_connections:
  - conn_name: System eth0
    ifname: eth0
    gw4_ignore_auto: true
  - conn_name: central-office1
    ifname: eth1
    ip4: '192.168.255.10/30'
    gw4: '192.168.255.9'
  - conn_name: office1-dev
    ifname: eth2
    ip4: '192.168.2.1/26'
  - conn_name: office1-test
    ifname: eth3
    ip4: '192.168.2.65/26'
  - conn_name: office1-managers
    ifname: eth4
    ip4: '192.168.2.129/26'
  - conn_name: office1-hardware
    ifname: eth5
    ip4: '192.168.2.193/26'
